stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

before_script:
  - apt-get update -qy
  - apt-get install -y openjdk-11-jdk
  - apt-get install -y maven
  - npm install -g allure-commandline

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    - mvn allure:report
  artifacts:
    paths:
      - target/allure-results/
      - target/site/allure-maven-plugin/
  only:
    - feature/NataliaFedchenko-CBATest
